SeanMcCrossanTUD/TUD-Group-Project

Testing github

This is testing github prod branch

test_git_hub

---

D22125039.md
README.md

create develop branch

---

python-da/dq-checks/src/data_quality_checker.py
python-da/dq-checks/tests/test_data_quality_checker.py

- Implement count_number_of_records in DataQualityChecker
- Add corresponding unit test

feat: Add count_number_of_records function and unit test

---

python-da/dq-checks/src/data_quality_checker.py
python-da/dq-checks/tests/test_data_quality_checker.py
python-da/requirements.txt

- Introduce z_score_outliers and iqr_outliers methods in DataQualityChecker class for outlier detection.
- z_score_outliers method identifies outliers based on Z-Scores, returning detailed information including row index, field name, outlier value, Z-Score, and threshold.
- iqr_outliers method utilizes the Interquartile Range (IQR) for outlier detection, providing comprehensive details on each outlier, including row index, field name, outlier value, and IQR bounds.
- Implement unit tests for both z_score_outliers and iqr_outliers methods, ensuring accurate and reliable outlier detection and information retrieval for each method.

Implement Outlier Detection Methods (Z-Score & IQR) and Corresponding Unit Tests

---

python-da/data-prep/src/__init__.py
python-da/data-prep/src/data_prep.py
python-da/data-prep/tests/__init__.py
python-da/data-prep/tests/test_data_prep.py

New folder structure created for DataCleaning functionalities, raw python scripts extracted from Jupyter notebooks and unit tests created using pytest

FAB-39-Auto-handle-outliers

---

python-da/dq-checks/run.py
python-da/dq-checks/run_tests.py
python-da/dq-checks/src/app.py
python-da/dq-checks/src/data_quality_checker.py
python-da/dq-checks/tests/test_app.py
python-da/requirements.txt

- Created app.py to initialise and configure the Flask API.
- Set up logging configuration for the application.
- Implemented a health check endpoint (/health) that returns the application's status and version.
- Added functionality to download CSV data from Azure Blob Storage and convert it into a Pandas DataFrame.
- Implemented data quality checks on the downloaded data and exposed the results through a new endpoint (/data-quality-check).
- Added test_app.py for unit testing.
- Implemented a fixture to set up a Flask test client before running tests.
- Added a unit test for the health check endpoint to ensure it returns the expected status code and data.
- Updated the outlier checks in data_quality_checker.py:
- Reset the index after dropping columns to maintain data integrity and …

feat: Initialise Flask API and Health Check Test

---

python-da/dq-checks/run.py
python-da/dq-checks/src/app.py

- Added `upload_results_to_azure` function for uploading data quality results to Azure Blob Storage.
- Function converts results to JSON, appends timestamp to filename, and handles errors during upload.
- Removed save to local folder

feat: Add Azure Blob Upload for Data Quality Results

---

python-da/dq-checks/run.py
python-da/dq-checks/src/app.py

- Created function to save results to json in folder location
- Json results saved so that team can work on dp dashboard and for data prep testing
- run.py file fixed so that it can run the app.

Save results to json

---

python-da/data-prep/src/app.py

- Implement a function in app.py to download JSON data from Azure Blob Storage, convert it to a Python dictionary, and handle potential errors gracefully. Set up logging for debugging and error tracking.
- Created app.py file for data prep module

feat: add Azure Blob JSON downloader in app.py

---

python-da/data-prep/src/app.py

- Added the function convert_outliers_dict_to_dataframe which takes the outliers dictionairy and converts it to dataframe

Fab -131-feat: add dict to pd dataframe for outliers

---

python-da/dq-checks/src/data_profiling_visuals.py
python-da/requirements.txt

- Data profiling class contains methods which create visuals from the data quality checker.
- Bar chart for missing values and bar chart for cardinality.
- Updated the requirements file to include visualisation packages

FAB-134: Created a data profiling class

---

python_da/data_prep/run.py
python_da/data_prep/src/app.py

FAB-95: Adding API for data prep

---

python_da/dq_checks/src/app.py
python_da/dq_checks/src/data_profiling_visuals.py

- Added functionality to generate and upload data profiling visuals to Azure
- Enhanced error handling for scenarios with empty or whitespace-only CSV data
-  Download 'dirty_startup_dataset.csv' when other dataset is blank (Will be removed after Friday)
- Edited DataProfilingVisuals to save visuals as io.Bytes.

FAB-137: Implemented image upload to Azure Blob Storage

---

python_da/data_prep/src/app.py
python_da/dq_checks/src/app.py
python_da/requirements.txt

- Updated requirements file
- Created functions for both data prep and data quality checks
- TO-DO: Refactor using configuration files
- TO-DO: Refactor creating azure class. Code in app is getting too messy and functions can be reused between the modules.

FAB-139: Implement new functions to push and get messages from azure

---

.gitignore

- Created a python virtual environment and added to gitignore

FAB-170: update gitignore file

---

Data Polish-Backend/Data-Polish-Backend/pom.xml
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DBCheckController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileUploadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/StoredProcedureController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/FileUploadService.java
Data Polish-Backend/Data-Polish-Backend/src/main/resources/application.properties
Data Polish-Backend/Data-Polish-Backend/src/main/resources/templates/error.html

- File import now does all the necessary connectivity things it's supposed to do
- returns proper status code instead of string
- returns JSON as output
- File structure of the code updated which now has separate controller package and service package

File Import API at perfect condition

---

python_da/data_prep/src/app.py
python_da/data_prep/tests/test_data_prep.py
python_da/dq_checks/src/app.py
python_da/dq_checks/tests/test_data_quality_checker.py
python_da/pyconfigurations/azure_config.json
python_da/requirements.txt
python_da/setup.py

- Added a configuration file to make refactoring code easier.
- Applied it to data prep and dq-checks module
- Fixed package imports in unit tests
- Discovered bug in data prep unit tests, jira FAB-206

FAB-205: Add configuration file

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileDownloadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/FileDownloadService.java

- added both file download controller and file download service files
- feature works properly return proper HTTP status code and output in JSON after querying DB

File Download Backend API

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataCleaningController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataProfilingController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileDownloadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/DataCleaningService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/DataProfilingService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/FileDownloadService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/FileUploadService.java
Data Polish-Backend/Data-Polish-Backend/src/main/resources/application.properties

DataCleaningController class done

Data Cleaning backend API

---

python_da/azure_package/src/azure_functions.py
python_da/data_prep/run_main.py
python_da/dq_checks/run_main.py

- Fixed data profiling main script
- Fixed azure functions bug
- Created data prep script

Fab 217 create main function for data prep

---

python_da/dq_checks/run_main.py

FAB-218: multiple folders bug fix

---

python_da/azure_package/src/azure_functions.py
python_da/dq_checks/testing_sql.py
python_da/pyconfigurations/sql_config.json
python_da/rds_sql_package/src/rds_sql_functions.py
python_da/requirements.txt
python_da/setup.py

- Created sql connector
- Updated run_main in data profiling

FAB-219: Connect to sql

---

python_da/data_prep/src/data_prep.py
python_da/data_prep/tests/test_data_prep.py

rename_column option to allow users change column names in the data frame with corresponding unit test.

FAB-173-Ability-to-rename-columns

---

python_da/data_prep/run_main.py
python_da/dq_checks/run_main.py

FAB-247: Made change to time of sleep

---

Frontend-Angular/data-polish-frontend/src/app/D3/data-types-chart/data-types-chart.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/data-types-chart/data-types-chart.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/data-types-chart/data-types-chart.component.spec.ts
Frontend-Angular/data-polish-frontend/src/app/D3/data-types-chart/data-types-chart.component.ts
Frontend-Angular/data-polish-frontend/src/app/app.module.ts

- Created components for data type
- Rotated bar chart
- Same as missing values but rotated

FAB-188: Creating data-types profiling chart

---

Frontend-Angular/data-polish-frontend/src/app/D3/missing-values-chart/missing-values-chart.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/missing-values-chart/missing-values-chart.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/missing-values-chart/missing-values-chart.component.spec.ts
Frontend-Angular/data-polish-frontend/src/app/D3/missing-values-chart/missing-values-chart.component.ts
Frontend-Angular/data-polish-frontend/src/app/app.module.ts
Frontend-Angular/data-polish-frontend/src/app/data-profile/data-profile.component.css
Frontend-Angular/data-polish-frontend/src/app/data-profile/data-profile.component.html
Frontend-Angular/data-polish-frontend/src/styles.css

- Chart created
- CSS sheets withing missing values componenent not working as expected, getting overwritten by global (FIX)
- Data profile HTML needs to be fixed and styled for being a dashboard
- IN PROGRESS, DO NOT MERGE

FAB-189: Create missing values d3 chart

---

python_da/dq_checks/azure_package/src/azure_functions.py
python_da/dq_checks/pyconfigurations/azure_config.json
python_da/dq_checks/pyconfigurations/sql_config.json
python_da/dq_checks/rds_sql_package/src/rds_sql_functions.py
python_da/dq_checks/run_main.py
python_da/dq_checks/src/meta_data_functions.py

- Added functions to data profile module
- Tested that it worked

FAB-249: Uploading meta data of dataset to azure for data preview

---

questionaires both qualitative and quantitative

created the surveys ages ago but i need them pulled

Fab 235 create quantitative survey

---

python_da/requirements.txt

Added the re python module to the requirements file, should fix the bug

FAB-250-Trimming-white-space-unit-test-failure

---

Project supporting Artifacts/test_data/example_output_col_clean_json.json

Sample json required from col cleaning

FAB-254: Sample json data

---

python_da/data_prep/src/data_prep.py
python_da/data_prep/tests/test_data_prep.py
python_da/requirements.txt

- Removed RE from requirements.txt (not needed)
- Imported RE in the class file (wasnt there how did it initially work?)
- Removed RE from test file
- Imported PCA functionality

FAB-263: Fixed bugs within code

---

python_da/data_prep/run_main.py

- Create apply column cleaning function that parses the json
- Subject to change in coming week but good start

FAB-260: Create apply column cleaning function

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataCleaningController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataPreviewController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileDownloadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileUploadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/resources/static/cors-test.html

cors global configuration for all java controllers
created html with javascript file to test cors from different ports, added comment on the file to carry out the test

Fab 268 spring boot cors global configuration

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/DataCleaningService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/DataProfilingService.java

changed naming for json file
fixed .json extension
fixed json file upload to blob

Fab 242 backend data preview column cleaning

---

python_da/data_prep/azure_package/src/azure_functions.py
python_da/data_prep/run_main.py
python_da/dq_checks/azure_package/src/azure_functions.py
python_da/dq_checks/run_main.py

- Created function to download excel from Blob
- Added to main

FAB-272: Allow users to upload excel files

---

Frontend-Angular/data-polish-frontend/src/app/D3/histogram/histogram.component.ts

Added ideal normal curve
Added colour legend

Fab 287 normal distribution chart improvement

---

Final_dq_metric_score_code.ipynb
Frontend-Angular/data-polish-frontend/src/app/D3/data-quality-metric/data-quality-metric.component.ts
Frontend-Angular/data-polish-frontend/src/app/D3/spider-chart/spider-chart.component.ts
Frontend-Angular/data-polish-frontend/src/app/app.module.ts
Frontend-Angular/data-polish-frontend/src/app/data-profile/data-profile.component.css
Frontend-Angular/data-polish-frontend/src/app/data-profile/data-profile.component.html

changes made are as follows,
- fixed dq metric chart ! wow its now working wooh wooh
- fixed duplication of components occurred after merging into main
- next is i removed all unnecessary code, still some to remove, but great progress
- finally there is a bug where the size of the graph is not == as the grid around the graph, this is a small error i will try to finish now , which will help us to see long graphs such as scatter plots or long bar charts. anyways when charts exceed the length of the width.

Fab 89 data quality scorecard

---

Project supporting Artifacts/test_data/column_actions.json
Project supporting Artifacts/test_data/dataset_actions.json

Fab 309 json data cleaning parameters

---

Data Polish-Backend/Data-Polish-Backend/pom.xml
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataCleaningController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataPreviewController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/DataProfileController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileDownloadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileUploadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/UserLoginController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/UserLogoutController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/UserRegistrationController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/UserLoginService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/UserLogoutService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/UserRegistrationService.java

- Added jwt dependencies to pom.xml
- Completed Login (JWT token creation)
- Completed logout (token moved to blacklist)
- Updated and added Authentication to all existing pages - file upload, data preview, profile, cleaning, file download

Fab 267 backend registration login

---

python_da/data_prep/run_main.py
python_da/dq_checks/src/data_quality_checker.py

Not ready until live json and container.

Fab 288 integrate data cleaning version 2

---

Frontend-Angular/data-polish-frontend/src/app/D3/cardinality/cardinality.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/cardinality/cardinality.component.ts
Frontend-Angular/data-polish-frontend/src/app/D3/spider-chart/spider-chart.component.ts

Added simple animation to the 
-DQ chart
-Completeness chart
-Consistency chart
-uniqueness chart
-readability chart
-spider chart 
:)

updated animation to our graphs , 6 graphs total

---

Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.ts
Frontend-Angular/data-polish-frontend/src/app/data-profile/data-profile.component.html
Frontend-Angular/data-polish-frontend/src/assets/sample.json

BUBBLE CHART FILTER AND NEW DATA CONNECTION :)

Fab 278 bubble chart

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/UserLoginController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/WebConfig.java
Frontend-Angular/data-polish-frontend/angular.json
Frontend-Angular/data-polish-frontend/package-lock.json
Frontend-Angular/data-polish-frontend/package.json
Frontend-Angular/data-polish-frontend/src/app/Services/login/login-service.service.spec.ts
Frontend-Angular/data-polish-frontend/src/app/Services/login/login-service.service.ts
Frontend-Angular/data-polish-frontend/src/app/Services/token.interceptor.ts
Frontend-Angular/data-polish-frontend/src/app/app.component.css
Frontend-Angular/data-polish-frontend/src/app/app.component.html
Frontend-Angular/data-polish-frontend/src/app/app.component.ts
Frontend-Angular/data-polish-frontend/src/app/app.module.ts
Frontend-Angular/data-polish-frontend/src/app/data-cleaning/rules/rules.component.ts
Frontend-Angular/data-polish-frontend/src/styles.css

Fab 297 log in

---

Data Polish-Backend/Data-Polish-Backend/pom.xml
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/FileDownloadController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/DataCleaningService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/FileDownloadService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/UserLoginService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/WebConfig.java

- storing tokens in DB for each user when they login instead of storing in local memory
- file conversion for file download, passing cases: blob- csv, user wants- csv; blob- xlsx, user wants- xlsx; blob- csv, user wants- xlsx; blob- xlsx, user wants- csv

Fab 331 backend token fix to allow multiple users && backend fix for file conversion

---

Frontend-Angular/data-polish-frontend/src/assets/DataCleaning_config.json

Help text for all functions in Data Cleaning Page with example usage

Fab 324 cleaning functions help text

---

Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.ts
python_da/data_prep/run_main.py
python_da/dq_checks/run_main.py

- Bug fix for remove duplicates
- Bug fix for zoom in bubble chart and title
- Bubble chart updated to include zoom in and out and tool tip added to include relative values as percentage

Fab 342 bubble chart bug fix

---

Frontend-Angular/data-polish-frontend/src/assets/DataCleaning_config.json
Frontend-Angular/data-polish-frontend/src/assets/Dataprofile_config.json
python_da/dq_checks/src/data_quality_evaluator.py

Bug fix and edit of help text.

Fab 343 readability too long to execute getting stuck

---

Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/bubble-chart/bubble-chart.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/correlation-scatter-plot/correlation-scatter-plot.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/correlation-scatter-plot/correlation-scatter-plot.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/histogram/histogram.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/histogram/histogram.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/outliers-scatter-plot/outliers-scatter-plot.component.css
Frontend-Angular/data-polish-frontend/src/app/D3/outliers-scatter-plot/outliers-scatter-plot.component.html
Frontend-Angular/data-polish-frontend/src/app/D3/outliers-scatter-plot/outliers-scatter-plot.component.ts
python_da/data_prep/run_main.py
python_da/dq_checks/run_main.py
python_da/dq_checks/src/data_quality_checker.py

Fixed hover issue in scatter plot
Redone the drop down menus put them to right and made them cleaner in dashboard 
Fixed couple of weird bugs in python

Fab 346 after user hovers on outlier the colour changes to a non outlier in outlier chart

---

Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/ForgetPasswordController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Controller/SetPasswordController.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/ForgetPasswordService.java
Data Polish-Backend/Data-Polish-Backend/src/main/java/com/example/Data/PolishBackend/Service/UserLoginService.java

- registration
- set password (new users)
- forget password

Fab 345 update registration api and create forget password api
